import { DBPreset } from "../types";

export const DB_PRESETS: DBPreset[] = [
    {
        id: "mysql",
        label: "MySQL",
        color: "#f97316",
        icon: "🐬",
        defaultPort: 3306,
        defaultVersion: "8.0",
        versions: ["8.4", "8.0", "5.7"],
        hasRootPassword: true,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "relational",
        description: "World's most popular open-source RDBMS",
    },
    {
        id: "mariadb",
        label: "MariaDB",
        color: "#c084fc",
        icon: "🦭",
        defaultPort: 3307,
        defaultVersion: "11.2",
        versions: ["11.4", "11.2", "10.11", "10.6"],
        hasRootPassword: true,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "relational",
        description: "MySQL-compatible, community-driven fork",
    },
    {
        id: "postgresql",
        label: "PostgreSQL",
        color: "#60a5fa",
        icon: "🐘",
        defaultPort: 5432,
        defaultVersion: "16",
        versions: ["17", "16", "15", "14", "13"],
        hasRootPassword: false,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "relational",
        description: "Advanced open-source object-relational database",
    },
    {
        id: "mssql",
        label: "SQL Server",
        color: "#ef4444",
        icon: "🪟",
        defaultPort: 1433,
        defaultVersion: "2022-latest",
        versions: ["2022-latest", "2019-latest", "2017-latest"],
        hasRootPassword: true,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "relational",
        description: "Microsoft's enterprise relational database",
    },
    {
        id: "mongodb",
        label: "MongoDB",
        color: "#4ade80",
        icon: "🍃",
        defaultPort: 27017,
        defaultVersion: "7.0",
        versions: ["7.0", "6.0", "5.0"],
        hasRootPassword: true,
        hasDatabase: true,
        hasUser: true,
        hasPassword: false,
        category: "nosql",
        description: "Document-oriented NoSQL database",
    },
    {
        id: "cassandra",
        label: "Cassandra",
        color: "#a78bfa",
        icon: "🎯",
        defaultPort: 9042,
        defaultVersion: "4.1",
        versions: ["4.1", "4.0", "3.11"],
        hasRootPassword: false,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "nosql",
        description: "Highly scalable distributed NoSQL database",
    },
    {
        id: "redis",
        label: "Redis",
        color: "#f87171",
        icon: "⚡",
        defaultPort: 6379,
        defaultVersion: "7.2",
        versions: ["7.4", "7.2", "7.0", "6.2"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: true,
        category: "cache",
        description: "In-memory data structure store & cache",
    },
    {
        id: "elasticsearch",
        label: "Elasticsearch",
        color: "#fbbf24",
        icon: "🔍",
        defaultPort: 9200,
        defaultVersion: "8.11.0",
        versions: ["8.11.0", "8.10.0", "7.17.0"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: true,
        category: "search",
        description: "Distributed search and analytics engine",
    },
    {
        id: "neo4j",
        label: "Neo4j",
        color: "#22d3ee",
        icon: "🕸️",
        defaultPort: 7474,
        defaultVersion: "5.15",
        versions: ["5.15", "5.0", "4.4"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: true,
        hasPassword: true,
        category: "graph",
        description: "Native graph database platform",
    },
    {
        id: "influxdb",
        label: "InfluxDB",
        color: "#34d399",
        icon: "📈",
        defaultPort: 8086,
        defaultVersion: "2.7",
        versions: ["2.7", "2.6", "1.8"],
        hasRootPassword: false,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "timeseries",
        description: "Purpose-built time series database",
    },
];

export const DB_CATEGORY_LABELS: Record<string, string> = {
    relational: "Relational",
    nosql: "NoSQL",
    cache: "Cache",
    search: "Search",
    timeseries: "Time Series",
    graph: "Graph",
};