import { DBPreset } from "../types";

export const DB_PRESETS: DBPreset[] = [
    // ─── Relational ──────────────────────────────────────────
    {
        id: "mysql",
        label: "MySQL",
        color: "#f97316",
        icon: "🐬",
        defaultPort: 3306,
        defaultVersion: "9.7",
        versions: ["9.7", "8.4", "8.0"],
        hasRootPassword: true,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "relational",
        description: "World's most popular open-source RDBMS",
    },
    {
        id: "mariadb",
        label: "MariaDB",
        color: "#c084fc",
        icon: "🦭",
        defaultPort: 3307,
        defaultVersion: "11.4",
        versions: ["11.7", "11.4", "10.11", "10.6"],
        hasRootPassword: true,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "relational",
        description: "MySQL-compatible, community-driven fork",
    },
    {
        id: "postgresql",
        label: "PostgreSQL",
        color: "#60a5fa",
        icon: "🐘",
        defaultPort: 5432,
        defaultVersion: "17",
        versions: ["17", "16", "15", "14"],
        hasRootPassword: false,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "relational",
        description: "Advanced open-source object-relational database",
    },
    {
        id: "mssql",
        label: "SQL Server",
        color: "#ef4444",
        icon: "🪟",
        defaultPort: 1433,
        defaultVersion: "2022-latest",
        versions: ["2022-latest", "2019-latest", "2017-latest"],
        hasRootPassword: true,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "relational",
        description: "Microsoft's enterprise relational database",
    },
    {
        id: "oracle",
        label: "Oracle XE",
        color: "#f87171",
        icon: "🔴",
        defaultPort: 1521,
        defaultVersion: "21.3.0-xe",
        versions: ["21.3.0-xe", "18.4.0-xe"],
        hasRootPassword: true,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "relational",
        description: "Oracle Database Express Edition",
    },
    {
        id: "sqlite",
        label: "SQLite (keygen)",
        color: "#94a3b8",
        icon: "🪶",
        defaultPort: 8080,
        defaultVersion: "latest",
        versions: ["latest"],
        hasRootPassword: false,
        hasDatabase: true,
        hasUser: false,
        hasPassword: false,
        category: "relational",
        description: "Lightweight embedded SQL database via web UI",
    },
    {
        id: "tidb",
        label: "TiDB",
        color: "#f43f5e",
        icon: "🦁",
        defaultPort: 4000,
        defaultVersion: "latest",
        versions: ["latest", "v8.1.0", "v7.5.0"],
        hasRootPassword: false,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "relational",
        description: "MySQL-compatible distributed HTAP database",
    },
    {
        id: "cockroachdb",
        label: "CockroachDB",
        color: "#6366f1",
        icon: "🪳",
        defaultPort: 26257,
        defaultVersion: "latest",
        versions: ["latest", "v24.1.0", "v23.2.0"],
        hasRootPassword: false,
        hasDatabase: true,
        hasUser: true,
        hasPassword: false,
        category: "relational",
        description: "Cloud-native distributed SQL with geo-partitioning",
    },
    {
        id: "yugabyte",
        label: "YugabyteDB",
        color: "#10b981",
        icon: "🌏",
        defaultPort: 5433,
        defaultVersion: "latest",
        versions: ["latest", "2.20.0.0"],
        hasRootPassword: false,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "relational",
        description: "Distributed SQL compatible with PostgreSQL & Cassandra",
    },
    {
        id: "singlestore",
        label: "SingleStore",
        color: "#a855f7",
        icon: "⚡",
        defaultPort: 3306,
        defaultVersion: "latest",
        versions: ["latest"],
        hasRootPassword: true,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "relational",
        description: "Real-time analytics database (formerly MemSQL)",
    },

    // ─── NoSQL Document ───────────────────────────────────────
    {
        id: "mongodb",
        label: "MongoDB",
        color: "#4ade80",
        icon: "🍃",
        defaultPort: 27017,
        defaultVersion: "8.0",
        versions: ["8.0", "7.0", "6.0"],
        hasRootPassword: true,
        hasDatabase: true,
        hasUser: true,
        hasPassword: false,
        category: "nosql",
        description: "Document-oriented NoSQL database",
    },
    {
        id: "couchdb",
        label: "CouchDB",
        color: "#ef4444",
        icon: "🛋️",
        defaultPort: 5984,
        defaultVersion: "3.4",
        versions: ["3.4", "3.3", "3.2"],
        hasRootPassword: true,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "nosql",
        description: "HTTP-based document database with sync",
    },
    {
        id: "couchbase",
        label: "Couchbase",
        color: "#ea580c",
        icon: "🧡",
        defaultPort: 8091,
        defaultVersion: "7.6.2",
        versions: ["7.6.2", "7.2.0", "7.1.0"],
        hasRootPassword: true,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "nosql",
        description: "Distributed multi-model document database",
    },
    {
        id: "rethinkdb",
        label: "RethinkDB",
        color: "#2563eb",
        icon: "🔄",
        defaultPort: 8080,
        defaultVersion: "latest",
        versions: ["latest", "2.4.4"],
        hasRootPassword: false,
        hasDatabase: true,
        hasUser: false,
        hasPassword: false,
        category: "nosql",
        description: "Real-time NoSQL with change feeds",
    },
    {
        id: "ravendb",
        label: "RavenDB",
        color: "#7c3aed",
        icon: "🐦",
        defaultPort: 8080,
        defaultVersion: "latest",
        versions: ["latest", "6.2", "6.0"],
        hasRootPassword: false,
        hasDatabase: true,
        hasUser: false,
        hasPassword: false,
        category: "nosql",
        description: "ACID document database with LINQ querying",
    },

    // ─── NoSQL Wide Column ────────────────────────────────────
    {
        id: "cassandra",
        label: "Cassandra",
        color: "#a78bfa",
        icon: "🎯",
        defaultPort: 9042,
        defaultVersion: "5.0",
        versions: ["5.0", "4.1", "4.0"],
        hasRootPassword: false,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "wide-column",
        description: "Highly scalable distributed NoSQL database",
    },
    {
        id: "scylladb",
        label: "ScyllaDB",
        color: "#06b6d4",
        icon: "🦑",
        defaultPort: 9042,
        defaultVersion: "6.2",
        versions: ["6.2", "6.1", "5.4"],
        hasRootPassword: false,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "wide-column",
        description: "Cassandra-compatible at 10x performance",
    },
    {
        id: "hbase",
        label: "HBase",
        color: "#eab308",
        icon: "🏠",
        defaultPort: 16010,
        defaultVersion: "latest",
        versions: ["latest"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: false,
        category: "wide-column",
        description: "Hadoop's distributed BigTable-like store",
    },

    // ─── Cache / Key-Value ────────────────────────────────────
    {
        id: "redis",
        label: "Redis",
        color: "#f87171",
        icon: "⚡",
        defaultPort: 6379,
        defaultVersion: "8.0",
        versions: ["8.0", "7.4", "7.2", "7.0"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: true,
        category: "cache",
        description: "In-memory data structure store & cache",
    },
    {
        id: "keydb",
        label: "KeyDB",
        color: "#f97316",
        icon: "🗝️",
        defaultPort: 6379,
        defaultVersion: "latest",
        versions: ["latest"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: true,
        category: "cache",
        description: "Multi-threaded Redis fork with active replication",
    },
    {
        id: "memcached",
        label: "Memcached",
        color: "#64748b",
        icon: "💨",
        defaultPort: 11211,
        defaultVersion: "1.6",
        versions: ["1.6", "1.5"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: false,
        category: "cache",
        description: "High-performance distributed memory cache",
    },
    {
        id: "dragonfly",
        label: "Dragonfly",
        color: "#10b981",
        icon: "🐉",
        defaultPort: 6379,
        defaultVersion: "latest",
        versions: ["latest", "v1.23.0", "v1.20.0"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: true,
        category: "cache",
        description: "Redis-compatible, 25x faster in-memory store",
    },

    // ─── Search ───────────────────────────────────────────────
    {
        id: "elasticsearch",
        label: "Elasticsearch",
        color: "#fbbf24",
        icon: "🔍",
        defaultPort: 9200,
        defaultVersion: "8.17.0",
        versions: ["9.0.0", "8.17.0", "8.15.0", "7.17.0"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: true,
        category: "search",
        description: "Distributed search and analytics engine",
    },
    {
        id: "opensearch",
        label: "OpenSearch",
        color: "#3b82f6",
        icon: "🔎",
        defaultPort: 9200,
        defaultVersion: "2.18.0",
        versions: ["2.18.0", "2.15.0", "2.11.0"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: true,
        hasPassword: true,
        category: "search",
        description: "AWS community fork of Elasticsearch",
    },
    {
        id: "meilisearch",
        label: "Meilisearch",
        color: "#ff5caa",
        icon: "⚡",
        defaultPort: 7700,
        defaultVersion: "latest",
        versions: ["latest", "v1.12", "v1.10"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: true,
        category: "search",
        description: "Blazing fast open-source search engine",
    },
    {
        id: "typesense",
        label: "Typesense",
        color: "#f43f5e",
        icon: "🎪",
        defaultPort: 8108,
        defaultVersion: "27.1",
        versions: ["27.1", "26.0", "0.25.2"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: true,
        category: "search",
        description: "Typo-tolerant instant search engine",
    },
    {
        id: "solr",
        label: "Apache Solr",
        color: "#d97706",
        icon: "☀️",
        defaultPort: 8983,
        defaultVersion: "9.8",
        versions: ["9.8", "9.7", "8.11"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: false,
        category: "search",
        description: "Enterprise search platform built on Lucene",
    },
    {
        id: "manticore",
        label: "Manticore",
        color: "#8b5cf6",
        icon: "🔱",
        defaultPort: 9306,
        defaultVersion: "latest",
        versions: ["latest", "6.3.6"],
        hasRootPassword: false,
        hasDatabase: true,
        hasUser: false,
        hasPassword: false,
        category: "search",
        description: "Percona-like search engine compatible with Sphinx",
    },

    // ─── Graph ────────────────────────────────────────────────
    {
        id: "neo4j",
        label: "Neo4j",
        color: "#22d3ee",
        icon: "🕸️",
        defaultPort: 7474,
        defaultVersion: "5.26",
        versions: ["2026.05", "5.26", "5.0", "4.4"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: true,
        hasPassword: true,
        category: "graph",
        description: "Native graph database platform",
    },
    {
        id: "arangodb",
        label: "ArangoDB",
        color: "#16a34a",
        icon: "🦔",
        defaultPort: 8529,
        defaultVersion: "3.12",
        versions: ["3.12", "3.11", "3.10"],
        hasRootPassword: true,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "graph",
        description: "Multi-model graph, document, and key-value DB",
    },
    {
        id: "janusgraph",
        label: "JanusGraph",
        color: "#7c3aed",
        icon: "🌐",
        defaultPort: 8182,
        defaultVersion: "latest",
        versions: ["latest", "1.0.0"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: false,
        category: "graph",
        description: "Scalable graph DB supporting various backends",
    },
    {
        id: "dgraph",
        label: "Dgraph",
        color: "#ec4899",
        icon: "♦️",
        defaultPort: 8080,
        defaultVersion: "latest",
        versions: ["latest", "v24.0.0", "v23.0.0"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: true,
        category: "graph",
        description: "GraphQL-native distributed graph database",
    },

    // ─── Time Series ──────────────────────────────────────────
    {
        id: "influxdb",
        label: "InfluxDB",
        color: "#34d399",
        icon: "📈",
        defaultPort: 8086,
        defaultVersion: "2.7",
        versions: ["3.0", "2.7", "2.6", "1.8"],
        hasRootPassword: false,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "timeseries",
        description: "Purpose-built time series database",
    },
    {
        id: "timescaledb",
        label: "TimescaleDB",
        color: "#fb923c",
        icon: "⏱️",
        defaultPort: 5432,
        defaultVersion: "2.17.2-pg17",
        versions: ["2.17.2-pg17", "2.16.0-pg16", "2.15.0-pg15"],
        hasRootPassword: false,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "timeseries",
        description: "PostgreSQL extension for time-series workloads",
    },
    {
        id: "questdb",
        label: "QuestDB",
        color: "#d946ef",
        icon: "⚗️",
        defaultPort: 9000,
        defaultVersion: "latest",
        versions: ["latest", "8.2.1", "7.4.0"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: false,
        category: "timeseries",
        description: "Fast SQL for time series & real-time analytics",
    },
    {
        id: "victoriametrics",
        label: "VictoriaMetrics",
        color: "#0ea5e9",
        icon: "📊",
        defaultPort: 8428,
        defaultVersion: "latest",
        versions: ["latest", "v1.105.0", "v1.100.0"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: false,
        category: "timeseries",
        description: "High-performance Prometheus-compatible TSDB",
    },
    {
        id: "prometheus",
        label: "Prometheus",
        color: "#f59e0b",
        icon: "🔥",
        defaultPort: 9090,
        defaultVersion: "latest",
        versions: ["latest", "v3.1.0", "v2.55.0"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: false,
        category: "timeseries",
        description: "Open-source monitoring and alerting toolkit",
    },
    {
        id: "m3db",
        label: "M3DB",
        color: "#6d28d9",
        icon: "🌡️",
        defaultPort: 7201,
        defaultVersion: "latest",
        versions: ["latest"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: false,
        category: "timeseries",
        description: "Uber's distributed time series database",
    },

    // ─── Vector / AI ──────────────────────────────────────────
    {
        id: "weaviate",
        label: "Weaviate",
        color: "#22c55e",
        icon: "🧠",
        defaultPort: 8080,
        defaultVersion: "latest",
        versions: ["latest", "1.27.0", "1.26.0"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: false,
        category: "vector",
        description: "Open-source vector search engine for AI",
    },
    {
        id: "qdrant",
        label: "Qdrant",
        color: "#f472b6",
        icon: "🎯",
        defaultPort: 6333,
        defaultVersion: "latest",
        versions: ["latest", "v1.13.0", "v1.12.0"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: false,
        category: "vector",
        description: "High-performance vector similarity search",
    },
    {
        id: "milvus",
        label: "Milvus",
        color: "#06b6d4",
        icon: "🌀",
        defaultPort: 19530,
        defaultVersion: "latest",
        versions: ["latest", "v2.5.0", "v2.4.0"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: false,
        category: "vector",
        description: "Cloud-native vector database for billion-scale embeddings",
    },
    {
        id: "chroma",
        label: "Chroma",
        color: "#f97316",
        icon: "🎨",
        defaultPort: 8000,
        defaultVersion: "latest",
        versions: ["latest", "0.6.0", "0.5.0"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: false,
        category: "vector",
        description: "AI-native embedding database",
    },
    {
        id: "pgvector",
        label: "pgvector",
        color: "#60a5fa",
        icon: "🐘",
        defaultPort: 5432,
        defaultVersion: "pg17",
        versions: ["pg17", "pg16", "pg15"],
        hasRootPassword: false,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "vector",
        description: "PostgreSQL extension for vector similarity search",
    },

    // ─── Message / Stream ─────────────────────────────────────
    {
        id: "kafka",
        label: "Apache Kafka",
        color: "#1a1a1a",
        icon: "📨",
        defaultPort: 9092,
        defaultVersion: "latest",
        versions: ["latest", "3.9.0", "3.8.0"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: false,
        category: "stream",
        description: "Distributed event streaming platform",
    },
    {
        id: "rabbitmq",
        label: "RabbitMQ",
        color: "#f97316",
        icon: "🐰",
        defaultPort: 5672,
        defaultVersion: "4.0-management",
        versions: ["4.0-management", "3.13-management", "3.12-management"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: true,
        hasPassword: true,
        category: "stream",
        description: "AMQP-based message broker",
    },
    {
        id: "nats",
        label: "NATS",
        color: "#27a2db",
        icon: "📡",
        defaultPort: 4222,
        defaultVersion: "latest",
        versions: ["latest", "2.10.24", "2.10.0"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: false,
        category: "stream",
        description: "Cloud-native messaging & streaming",
    },
    {
        id: "pulsar",
        label: "Apache Pulsar",
        color: "#4f46e5",
        icon: "💫",
        defaultPort: 6650,
        defaultVersion: "latest",
        versions: ["latest", "3.3.0", "3.2.0"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: false,
        category: "stream",
        description: "Multi-tenant distributed pub-sub messaging",
    },

    // ─── NewSQL / OLAP ────────────────────────────────────────
    {
        id: "clickhouse",
        label: "ClickHouse",
        color: "#ffcc00",
        icon: "🖱️",
        defaultPort: 8123,
        defaultVersion: "26.6",
        versions: ["26.6", "26.3", "25.8", "24.12"],
        hasRootPassword: true,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "olap",
        description: "Blazing fast columnar OLAP database",
    },
    {
        id: "druid",
        label: "Apache Druid",
        color: "#dc2626",
        icon: "🦣",
        defaultPort: 8888,
        defaultVersion: "latest",
        versions: ["latest", "31.0.0", "30.0.0"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: false,
        category: "olap",
        description: "Real-time analytics on large datasets",
    },
    {
        id: "starrocks",
        label: "StarRocks",
        color: "#e11d48",
        icon: "⭐",
        defaultPort: 9030,
        defaultVersion: "latest",
        versions: ["latest", "3.4.0", "3.3.0"],
        hasRootPassword: false,
        hasDatabase: true,
        hasUser: true,
        hasPassword: false,
        category: "olap",
        description: "Next-gen sub-second MPP OLAP database",
    },
    {
        id: "duckdb",
        label: "DuckDB (Harlequin)",
        color: "#fbbf24",
        icon: "🦆",
        defaultPort: 4213,
        defaultVersion: "latest",
        versions: ["latest"],
        hasRootPassword: false,
        hasDatabase: true,
        hasUser: false,
        hasPassword: false,
        category: "olap",
        description: "In-process analytical database",
    },

    // ─── Serverless / Edge ────────────────────────────────────
    {
        id: "surrealdb",
        label: "SurrealDB",
        color: "#ff00a0",
        icon: "🌌",
        defaultPort: 8000,
        defaultVersion: "latest",
        versions: ["latest", "v2.1.0", "v2.0.0"],
        hasRootPassword: true,
        hasDatabase: true,
        hasUser: true,
        hasPassword: true,
        category: "multi-model",
        description: "Multi-model cloud-native database language",
    },
    {
        id: "fauna",
        label: "FaunaDB",
        color: "#391cd9",
        icon: "🦋",
        defaultPort: 8443,
        defaultVersion: "latest",
        versions: ["latest"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: false,
        category: "multi-model",
        description: "Serverless distributed document-relational DB",
    },
    {
        id: "edgedb",
        label: "EdgeDB",
        color: "#4f46e5",
        icon: "🔷",
        defaultPort: 5656,
        defaultVersion: "latest",
        versions: ["latest", "6.0", "5.0"],
        hasRootPassword: false,
        hasDatabase: true,
        hasUser: false,
        hasPassword: false,
        category: "multi-model",
        description: "Next-gen graph-relational database",
    },

    // ─── Observability / Logs ─────────────────────────────────
    {
        id: "loki",
        label: "Grafana Loki",
        color: "#f97316",
        icon: "🪵",
        defaultPort: 3100,
        defaultVersion: "latest",
        versions: ["latest", "3.3.0", "3.2.0"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: false,
        hasPassword: false,
        category: "logs",
        description: "Horizontally scalable log aggregation system",
    },
    {
        id: "opensearch-dashboard",
        label: "OpenSearch Dashboards",
        color: "#3b82f6",
        icon: "📊",
        defaultPort: 5601,
        defaultVersion: "latest",
        versions: ["latest", "2.18.0", "2.15.0", "2.11.0"],
        hasRootPassword: false,
        hasDatabase: false,
        hasUser: true,
        hasPassword: true,
        category: "logs",
        description: "Visualization and dashboards for OpenSearch",
    },
];

export const DB_CATEGORY_LABELS: Record<string, string> = {
    relational: "Relational",
    nosql: "NoSQL",
    "wide-column": "Wide Column",
    cache: "Cache",
    search: "Search",
    timeseries: "Time Series",
    graph: "Graph",
    vector: "Vector / AI",
    stream: "Streams",
    olap: "OLAP",
    "multi-model": "Multi-Model",
    logs: "Logs & Observability",
};
