use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(default, rename_all = "camelCase")]
pub struct UserConfig {
    pub first_name: String,
    pub last_name: String,
    pub email: String,
    pub username: String,
    pub bio: String,
    pub company: String,
    pub website: String,
    pub avatar: Option<String>,
    pub github: String,
    pub twitter: String,
    pub linkedin: String,
    pub theme: String,
    pub accent_color: String,
    pub sidebar_collapsed: bool,
    pub font_size: String,
    pub animations: bool,
    pub hive_path: String,
    pub default_projects_path: String,
    pub hive_data_path: String,
    pub domain_tld: String,
    pub dns_resolver: String,
    pub proxy_port: u16,
    pub auto_start_proxy: bool,
    pub launch_on_login: bool,
    pub start_services_on_launch: bool,
    pub start_last_projects: bool,
    pub minimize_to_tray: bool,
    pub email_notifications: bool,
    pub desktop_notifications: bool,
    pub sound_effects: bool,
    pub auto_update: bool,
    pub telemetry: bool,
    pub user_code: String,
    pub github_starred: bool,
    pub onboarding_complete: bool,
}

impl Default for UserConfig {
    fn default() -> Self {
        Self {
            first_name: String::new(),
            last_name: String::new(),
            email: String::new(),
            username: String::new(),
            bio: String::new(),
            company: String::new(),
            website: String::new(),
            avatar: None,
            github: String::new(),
            twitter: String::new(),
            linkedin: String::new(),
            theme: "dark".to_string(),
            accent_color: "#F59E0B".to_string(),
            sidebar_collapsed: false,
            font_size: "medium".to_string(),
            animations: true,
            hive_path: "~/.hive".to_string(),
            default_projects_path: "~/Projects".to_string(),
            hive_data_path: "~/.hive".to_string(),
            domain_tld: "test".to_string(),
            dns_resolver: "auto".to_string(),
            proxy_port: 80,
            auto_start_proxy: true,
            launch_on_login: true,
            start_services_on_launch: true,
            start_last_projects: false,
            minimize_to_tray: true,
            email_notifications: true,
            desktop_notifications: true,
            sound_effects: false,
            auto_update: true,
            telemetry: false,
            user_code: String::new(),
            github_starred: false,
            onboarding_complete: false,
        }
    }
}