mod core;
mod modules;
mod tray;
mod types;

pub use core::*;
pub use modules::*;
use tauri::Manager;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    modules::laravel::cleanup_orphaned_servers();

    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_autostart::init(
            tauri_plugin_autostart::MacosLauncher::LaunchAgent,
            Some(vec!["--minimized"]),
        ))
        .plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.show();
                let _ = window.set_focus();
            }
        }))
        .setup(|app| {
            let handle = app.handle().clone();
            let _ = tray::setup_tray(&handle);
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            check_user_config_exists,
            get_user_config,
            save_user_config,
            initialize_hive,
            complete_onboarding,
            get_onboarding_status,
            detect_php,
            detect_node,
            get_installed_runtimes,
            install_runtime,
            get_available_links,
            uninstall_runtime,
            check_and_install_dependencies,
            get_os,
            get_arch,
            kill_process,
            execute_shell_command,
            execute_shell_streaming,
            check_command_exists,
            list_all_projects,
            remove_project,
            get_existing_projects,
            check_project_exists,
            check_package_manager,
            install_package_manager,
            create_laravel_project,
            create_nextjs_project,
            create_nodejs_project,
            create_php_project,
            create_react_project,
            create_static_project,
            create_vite_project,
            create_vue_project,
            create_wordpress_project,
            fetch_wordpress_tags,
            download_wordpress_zip,
            extract_zip,
            start_wordpress_project,
            stop_wordpress_project,
            restart_wordpress_project,
            get_wordpress_server_status,
            get_wordpress_plugins,
            get_wordpress_themes,
            get_wordpress_logs,
            start_laravel_project,
            stop_laravel_project,
            restart_laravel_project,
            is_laravel_running,
            get_laravel_server_status,
            get_all_running_servers,
            get_server_logs,
            clear_server_logs,
            start_php_project,
            stop_php_project,
            restart_php_project,
            get_php_server_status,
            get_php_info,
            run_artisan_command,
            get_artisan_commands,
            get_artisan_commands_with_details,
            get_queue_workers,
            get_queue_stats,
            get_queue_connection_info,
            get_queue_worker_logs,
            start_queue_worker,
            stop_queue_worker,
            restart_queue_worker,
            run_queue_command,
            get_failed_jobs,
            retry_failed_job,
            retry_all_failed_jobs,
            forget_failed_job,
            flush_failed_jobs,
            clear_queue,
            pause_queue,
            resume_queue,
            get_scheduled_tasks,
            run_scheduled_task,
            run_all_scheduled_tasks,
            get_project_logs,
            clear_project_logs,
            tail_project_logs,
            get_installed_packages,
            install_package,
            remove_package,
            update_package,
            search_packages,
            get_package_details,
            get_database_info,
            restart_database,
            backup_database,
            export_database_sql,
            check_deployer_installed,
            install_deployer,
            run_deployment,
            run_deploy_rollback,
            run_deploy_unlock,
            get_deploy_config,
            save_deploy_config,
            get_deploy_php_content,
            save_deploy_php_content,
            create_deploy_php,
            get_system_metrics,
            read_project_file,
            detect_cloudflared,
            check_cloudflared_installed,
            install_cloudflared,
            get_tunnel_config,
            save_tunnel_auth_token,
            delete_tunnel_auth_token,
            start_tunnel,
            start_quick_tunnel,
            stop_tunnel,
            stop_all_tunnels,
            get_tunnel_status,
            get_all_active_tunnels,
            get_tunnel_history,
            get_tunnel_session,
            detect_docker,
            get_docker_install_url,
            install_docker_linux,
            list_docker_containers,
            inspect_container,
            start_docker_container,
            stop_docker_container,
            restart_docker_container,
            remove_docker_container,
            pause_container,
            unpause_container,
            rename_container,
            update_container,
            kill_container,
            get_container_logs,
            get_container_stats,
            get_container_processes,
            commit_container,
            export_container,
            copy_from_container,
            copy_to_container,
            create_database_container,
            pull_docker_image,
            list_images,
            remove_image,
            prune_images,
            list_docker_volumes,
            list_docker_volumes_detailed,
            create_volume,
            remove_docker_volume,
            prune_volumes,
            list_networks,
            create_network,
            remove_network,
            connect_container_to_network,
            disconnect_container_from_network,
            get_docker_system_info,
            prune_system,
            prune_containers,
            execute_sql_in_container,
            backup_database_container,
            run_docker_compose,
            stop_docker_compose,
            list_compose_projects,
            exec_in_container,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
